### ISSUE TITLE
应用后不生效

### ISSUE THREAD

**Issue by NXN-MAX** [mysll/Synology_Photos_Face_Inject#1]
按步骤执行后，重建索引，还是没有识别，尝试重启依旧。
仅对某些版本生效吗？

CPU：i3 8100

918+
DSM 7.1-42661 update4

 Synology Photos
1.3.0-0317

**Comment by bslc981010** [comment]
同不生效，一直卡在还有XXX张照片待发现。

CPU：N3700

918+
DSM 7.0.1-42218

Synologu Photos
1.3.0-0317

**Comment by NXN-MAX** [comment]
> 同不生效，一直卡在还有XXX张照片待发现。
> 
> CPU：N3700
> 
> 918+ DSM 7.0.1-42218
> 
> Synologu Photos 1.3.0-0317

@bslc981010 
那应该是你的照片太多了，我的是检索完了都没有识别到人物。

**Comment by bslc981010** [comment]
> 

但是他XXX的数字一直没在变，没有减少呀。重建了缓存XXX会先缓慢增加到两倍，然后减少到原来的数字，再次卡住。。

**Comment by bslc981010** [comment]
> > 同不生效，一直卡在还有XXX张照片待发现。
> > CPU：N3700
> > 918+ DSM 7.0.1-42218
> > Synologu Photos 1.3.0-0317
> 
> @bslc981010 那应该是你的照片太多了，我的是检索完了都没有识别到人物。


但是他XXX的数字一直没在变，没有减少。。。
重建了缓存XXX会先缓慢增加到两倍，然后减少到原来的数字，再次卡住。。

**Comment by mysll** [comment]
新版本还没有测试过，上个版本是可以的。检索完没有识别到人物，可以单独点开图片看看图片的标签有没有变化。

**Comment by NXN-MAX** [comment]
> 新版本还没有测试过，上个版本是可以的。检索完没有识别到人物，可以单独点开图片看看图片的标签有没有变化。

@mysll 
新版本测试可以！
Synology Photos
1.3.0-0317
原来是我相同人物的照片仅有一张，所以没有分类到人物相册里，点开照片后可以看到识别了人物。
